package sqlbuilder

/**
 * Primary interface to be used as a stateless prototype.
 *
 * @author Laurent Van der Linden
 */
public interface SqlBuilder {
    public fun select(): Select
    public fun insert(): Insert
    public fun delete(): Delete
    public fun update(): Update

    /**
     * Insert or Update a bean by looking for an ID field.
     * After an insert, the autogenerated id is set on the result
     * @param bean DTO with an Integer or Long 'id' field
     * @param <T> type of the bean
     * @return the same bean with the id set
     */
    public fun <T : Any> save(bean: T, vararg excludedFields: String): T
    /**
     * Start a transaction with default isolation.
     */
    public fun startTransaction()
    /**
     * Start a transaction using an isolationlevel other than TRANSACTION_READ_COMMITTED
     * @param isolationLevel Connection.TRANSACTION_...
     */
    public fun startTransaction(isolationLevel: Int, readonly: Boolean)
    public fun commitTransaction()
    /**
     * This must be called in the a finally clause whenever you have started a transaction.
     * <br/>If commitTransaction has already been called, it will only cleanup resources,
     * else it will rollback the transaction.
     */
    public fun endTransaction()
    public fun purgeCache(cacheId: String)
    public fun purgeAllCaches()

    public var configuration: Configuration
}
